run:
  skip-dirs:
    - vendor
  modules-download-mode: vendor

linters:
  disable-all: true #so that lint version bumps don't change results
  enable:
    - errcheck
    - exportloopref
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - wastedassign